version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - mynetwork

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  redis:
    image: redis:latest
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongodb_data: