version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - DB_URL=mongodb://mongodb:27017/kota
      - REDISCLOUD_URL=redis
      - ZEPTOMAIL_API_KEY=yA6KbHtS7Q2iwj8FQEM81pOD84o1/6gxjH/ktS7jfcEkLtm33KFtgRRodIe5JjbeiofZta5Za9gYdYC4udAKesYzYdYAepTGTuv4P2uV48xh8ciEYNYmhZSsALIWGqRMchsiCSo2RPEjWA==
      - ZEPTOMAIL_DOMAIN=noreply@geelgeworden.nl
      - JWT_SECRET=ewinfewnjifiewjbnfiewenwinfewinjewew
      - CLIENT_URL=http://localhost:5173/verify/
      - CLOUDINARY_API_KEY=183515467334351
      - CLOUDINARY_API_SECRET=an5k38ts6Qt2keTXcMrXQ9LM_Ik
      - CLOUDINARY_CLOUD_NAME=lcu-feeding
      # Add other environment variables as needed
    depends_on:
      - mongodb
      - redis
    networks:
      - mynetwork

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  redis:
    image: redis:latest
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongodb_data:
