name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Add your EC2 instance public IP as a secret
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key as a secret
          port: 22
          script: |
            cd apps/gotbot
            git pull
            sudo docker compose build
            sudo docker compose up -d
